### ISSUE TITLE
Sonic Pi not launching

### ISSUE THREAD

**Issue by vlee489** [gbaman/RaspberryPi-LTSP#43]
When I launch Sonic Pi nothing happen and when in the *sonic-pi* command in the terminal it says that the file doesn't exist.

I am using the newest version of RaspberryPi-ltsp.

I'll be bring the server on Saturday.

**Comment by gbaman** [comment]
Have you done an ```Update-All``` any time recently? Goes through the full install list so should sort it out unless there is an issue with Sonic-pi itself

**Comment by vlee489** [comment]
If that's the thing it asks you to do after a update then yes

**Comment by gbaman** [comment]
Weird, try 
```sudo ltsp-chroot --arch armhf dpkg-reconfigure sonic-pi```
Will reconfigure the package, if you get an error about Sonic-pi not being installed, try these 2 commands
```sudo ltsp-chroot --arch armhf apt-get purge sonic-pi```
```sudo ltsp-chroot --arch armhf apt-get install sonic-pi```

**Comment by vlee489** [comment]
On the server or the pi's?

**Comment by gbaman** [comment]
Everything is done on the server.
```sudo ltsp-chroot --arch armhf``` means run command in the virtual Pi OS. 
http://pi-ltsp.net/advanced/editing-outside.html

**Comment by vlee489** [comment]
Thanks I'll try that when I get in ti school tomorrow

**Comment by vlee489** [comment]
We have found the problem. Currently it isn't a problem on Raspberry pi LTSP but it is that but the foundation haven't realsed the software to see how to fix it.

**Comment by ryanteck** [comment]
Temporary fix can be done by installing the package

libqt4-network

**Comment by gbaman** [comment]
Can confirm this fixes the issue

**Comment by gbaman** [comment]
Can confirm a bugfix workaround has now been added in Release 0.10.39 https://github.com/gbaman/RaspberryPi-LTSP/commit/aa27c90312ed42930e1bffd188035a021d09f3e3
Just upgrade your Raspi-LTSP and make sure to accept the packages update.
