### ISSUE TITLE
Keyboard and mouse not working 

### ISSUE THREAD

**Issue by mombe090** [gbaman/RaspberryPi-LTSP#51]
Hello mister gbaman I have installed pinet server 1.2.9 on Ubuntu 16.04 successfully. 
The problem is after flashy the pibout file on the sdcard and power on raspberry pi3  we are unable to use the keyboard and the mouse. 
Already past one week on but no solutions please help us.

**Comment by gbaman** [comment]
RaspberryPi-LTSP is no longer supported/maintained, please use [PiNet](http://pinet.org.uk) and log any issues over on the main [PiNet Github Project](https://github.com/pinet/pinet).
