### ISSUE TITLE
wireless raspberry pi classroom

### ISSUE THREAD

**Issue by fabubmz07** [gbaman/RaspberryPi-LTSP#52]
is it possible to connect a pinet server wirelessly to a raspberry pi? I am currently working on a raspberry pi wireless classroom project (server client based).
students user accounts are stored on the central pinet server with automated backup.

**Comment by fabubmz07** [comment]
i just wanted to connect 2 pis and one main server with a single wireless connection

**Comment by gbaman** [comment]
This repository is no longer maintained, the PiNet repository can be found over at https://github.com/pinet/pinet

As is noted in many places on the PiNet website, no PiNet does not support booting over wifi. For more information, please read the [PiNet FAQ](http://pinet.org.uk/articles/faq.html).
